Visual Cycle - First iteration
HappyPorch/reuse-standard-tools pull request #1
Opened 2020-12-07 19:35 UTC by pedroyan

https://www.loom.com/share/cfa49aa93f9d4fbb898da2a74a908b77

TODOs on next iteration:
- Error messages
- Render multiple cycles described in the data source (is it needed?)

2020-12-07 20:18 UTC, barryokane requested changes
Excellent work :)

Two (new) change requests...

2020-12-07 20:18 UTC, barryokane commented on js/main.js
> +    "https://raw.githubusercontent.com/reath-id/reuse.id/f/lifecycle/v0.1-alpha/standard/codelists/activity_types.csv",
Can we change this URL to the reuse-standard.org URL please? (Otherwise it will break when branches in repo change)

2020-12-07 20:18 UTC, barryokane commented on js/main.js
> +  _drawTitle("Example Reuse Cycle");
I forgot : this text should come from the "name" value of the source cycle json

2020-12-09 17:08 UTC, barryokane approved these changes

2020-12-11 10:59 UTC, barryokane approved these changes

2022-08-27 18:52 UTC, pedroyan commented
Closing this because it looks a little stale lol :)

2022-08-27 18:52 UTC, closed without merging